name: Makefile CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Building
      run: make pytorch
      
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - uses: actions/upload-artifact@v3
#       with:
#         name: Images_folder
#         path: /usr/bin/git
        
      

