name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Building
      run: make pytorch
      
    - uses: actions/upload-artifact@v3
      with:
        name: Images_folder
        path: /home/runner/work/
