name: Makefile CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Building
      run: make pytorch_builder
      # run: make pytorch
      


    - uses: actions/upload-artifact@v3
      with:
        name: Wheel_Builds
        # path: /usr/bin/git
        path: /current/build
        
      

